export type HypothesisCategory =
  | "performance"
  | "team_relative"
  | "context"
  | "composition"
  | "meta"
  | "trend";

export type HypothesisDataKey =
  | "result"
  | "map"
  | "mode"
  | "hero"
  | "player_stats"
  | "hero_detail"
  | "team_comp"
  | "manual_context"
  | "patch"
  | "meta_snapshot"
  | "profile_snapshot"
  | "duo_link"
  | "session_context"
  | "replay_timeline";

export type HypothesisPriority = "high" | "medium" | "explore";

export type HypothesisTemplate = {
  id: string;
  category: HypothesisCategory;
  title: string;
  question: string;
  rule: string;
  requiredData: HypothesisDataKey[];
  minSamples: number;
  priority: HypothesisPriority;
};

export const HYPOTHESIS_CATEGORY_META: Record<
  HypothesisCategory,
  { label: string; description: string }
> = {
  performance: {
    label: "개인 퍼포먼스",
    description: "내 플레이 지표 변화와 승패의 관계",
  },
  team_relative: {
    label: "팀 상대값",
    description: "팀 안에서 내가 차지한 비중과 상대 역할군 대비 차이",
  },
  context: {
    label: "맵 · 상황",
    description: "맵, 모드, 선공/선수비 등 경기 맥락",
  },
  composition: {
    label: "조합",
    description: "아군/상대 영웅과 내 영웅의 상호작용",
  },
  meta: {
    label: "패치 · 메타",
    description: "패치와 외부 메타 변화가 개인 성과에 미친 영향",
  },
  trend: {
    label: "장기 변화",
    description: "최근 폼, 티어, 플레이 습관과 듀오 효과의 변화",
  },
};

export const HYPOTHESIS_DATA_LABELS: Record<HypothesisDataKey, string> = {
  result: "승패",
  map: "맵",
  mode: "게임 모드",
  hero: "내 영웅",
  player_stats: "10인 스코어보드",
  hero_detail: "내 영웅 상세",
  team_comp: "양 팀 영웅 조합",
  manual_context: "선공/선수비·세부맵",
  patch: "패치",
  meta_snapshot: "공식 메타",
  profile_snapshot: "프로필 스냅샷",
  duo_link: "듀오 경기 연결",
  session_context: "세션 맥락",
  replay_timeline: "리플레이 타임라인",
};

export const PREDEFINED_HYPOTHESES: HypothesisTemplate[] = [
  {
    id: "perf-deaths-above-average",
    category: "performance",
    title: "데스 증가와 승률",
    question: "내 평균보다 데스/10분이 증가한 경기에서 승률이 낮아지는가?",
    rule: "deaths_per_10 > personal_baseline → compare win rate",
    requiredData: ["result", "player_stats"],
    minSamples: 30,
    priority: "high",
  },
  {
    id: "perf-elims-above-average",
    category: "performance",
    title: "처치 증가와 승률",
    question: "내 평균보다 처치/10분이 높은 경기에서 승률이 달라지는가?",
    rule: "elims_per_10 > personal_baseline → compare win rate",
    requiredData: ["result", "player_stats"],
    minSamples: 30,
    priority: "high",
  },
  {
    id: "perf-assists-above-average",
    category: "performance",
    title: "도움 증가와 승률",
    question: "도움/10분이 높은 경기에서 승률이 달라지는가?",
    rule: "assists_per_10 > personal_baseline → compare win rate",
    requiredData: ["result", "player_stats"],
    minSamples: 30,
    priority: "medium",
  },
  {
    id: "perf-damage-above-average",
    category: "performance",
    title: "피해량 증가와 승률",
    question: "피해/10분이 내 평소보다 높은 경기에서 승률이 달라지는가?",
    rule: "damage_per_10 > personal_baseline → compare win rate",
    requiredData: ["result", "player_stats"],
    minSamples: 30,
    priority: "high",
  },
  {
    id: "perf-healing-above-average",
    category: "performance",
    title: "치유량 증가와 승률",
    question: "치유/10분이 내 평소보다 높은 경기에서 승률이 달라지는가?",
    rule: "healing_per_10 > personal_baseline → compare win rate",
    requiredData: ["result", "player_stats"],
    minSamples: 30,
    priority: "medium",
  },
  {
    id: "perf-mitigation-above-average",
    category: "performance",
    title: "피해 경감과 승률",
    question: "피해 경감/10분이 높은 경기에서 승률이 달라지는가?",
    rule: "mitigation_per_10 > personal_baseline → compare win rate",
    requiredData: ["result", "player_stats"],
    minSamples: 30,
    priority: "medium",
  },
  {
    id: "perf-accuracy",
    category: "performance",
    title: "명중률 변화와 승률",
    question: "내 영웅별 평균보다 명중률이 높은 경기에서 승률이 높아지는가?",
    rule: "accuracy > hero_baseline → compare win rate",
    requiredData: ["result", "hero", "hero_detail"],
    minSamples: 25,
    priority: "medium",
  },
  {
    id: "perf-crit",
    category: "performance",
    title: "치명타 지표와 승률",
    question: "치명타 관련 지표가 좋은 경기에서 승률이 달라지는가?",
    rule: "critical_metric > hero_baseline → compare win rate",
    requiredData: ["result", "hero", "hero_detail"],
    minSamples: 25,
    priority: "explore",
  },

  {
    id: "team-damage-share",
    category: "team_relative",
    title: "팀 딜 비중과 승률",
    question: "팀 전체 피해 중 내 비율이 높을 때 승률이 달라지는가?",
    rule: "my_damage / team_damage → grouped win rate",
    requiredData: ["result", "player_stats"],
    minSamples: 30,
    priority: "high",
  },
  {
    id: "team-heal-share",
    category: "team_relative",
    title: "팀 치유 비중과 승률",
    question: "팀 전체 치유 중 내 비율이 높을 때 승률이 달라지는가?",
    rule: "my_healing / team_healing → grouped win rate",
    requiredData: ["result", "player_stats"],
    minSamples: 30,
    priority: "medium",
  },
  {
    id: "team-death-share",
    category: "team_relative",
    title: "팀 데스 비중과 승률",
    question: "팀 전체 데스 중 내 비율이 높아질수록 승률이 낮아지는가?",
    rule: "my_deaths / team_deaths → grouped win rate",
    requiredData: ["result", "player_stats"],
    minSamples: 30,
    priority: "high",
  },
  {
    id: "team-role-diff",
    category: "team_relative",
    title: "같은 역할 상대와 성과 차이",
    question: "같은 역할의 상대보다 내 핵심 지표가 우세할 때 승률이 달라지는가?",
    rule: "my_role_metric - opponent_role_metric → win rate",
    requiredData: ["result", "player_stats", "team_comp"],
    minSamples: 35,
    priority: "high",
  },
  {
    id: "team-performance-spread",
    category: "team_relative",
    title: "팀 내 퍼포먼스 편차",
    question: "팀원 간 성과 편차가 큰 경기에서 승률이 달라지는가?",
    rule: "team_metric_dispersion → compare win rate",
    requiredData: ["result", "player_stats"],
    minSamples: 40,
    priority: "explore",
  },
  {
    id: "team-my-outlier",
    category: "team_relative",
    title: "내 성과가 팀 평균에서 벗어난 정도",
    question: "내 지표가 팀 평균보다 크게 높거나 낮을 때 경기 결과가 달라지는가?",
    rule: "my_metric z-score within team → compare result",
    requiredData: ["result", "player_stats"],
    minSamples: 40,
    priority: "explore",
  },

  {
    id: "context-map",
    category: "context",
    title: "맵별 승률 차이",
    question: "특정 맵에서 내 승률이 전체 평균과 반복적으로 다른가?",
    rule: "map_name → compare win rate against personal baseline",
    requiredData: ["result", "map"],
    minSamples: 40,
    priority: "high",
  },
  {
    id: "context-mode",
    category: "context",
    title: "게임 모드별 승률 차이",
    question: "호위, 점령, 쟁탈 등 모드별로 내 승률 차이가 있는가?",
    rule: "game_mode → grouped win rate",
    requiredData: ["result", "mode"],
    minSamples: 40,
    priority: "medium",
  },
  {
    id: "context-map-hero",
    category: "context",
    title: "맵 × 내 영웅",
    question: "같은 영웅이라도 특정 맵에서 성과와 승률이 달라지는가?",
    rule: "map_name × my_hero → interaction effect",
    requiredData: ["result", "map", "hero"],
    minSamples: 60,
    priority: "high",
  },
  {
    id: "context-attack-defense",
    category: "context",
    title: "선공/선수비 효과",
    question: "같은 맵에서 선공과 선수비에 따라 승률이 달라지는가?",
    rule: "side × map_name → compare win rate",
    requiredData: ["result", "map", "manual_context"],
    minSamples: 50,
    priority: "medium",
  },
  {
    id: "context-control-submap",
    category: "context",
    title: "쟁탈 세부 맵",
    question: "쟁탈의 특정 세부 맵에서 반복적으로 성과 차이가 발생하는가?",
    rule: "control_submap → grouped result",
    requiredData: ["result", "manual_context"],
    minSamples: 50,
    priority: "medium",
  },
  {
    id: "context-round-order",
    category: "context",
    title: "세부 맵 진행 순서",
    question: "세트 또는 세부 맵 진행 순서에 따라 이후 승률이 달라지는가?",
    rule: "round_sequence → next_round / match result",
    requiredData: ["result", "manual_context"],
    minSamples: 60,
    priority: "explore",
  },
  {
    id: "context-match-length",
    category: "context",
    title: "긴 경기와 성과 변화",
    question: "경기 시간이 길어질수록 내 데스나 효율이 악화되는가?",
    rule: "match_duration × personal_metrics → result",
    requiredData: ["result", "player_stats"],
    minSamples: 40,
    priority: "explore",
  },

  {
    id: "comp-ally-hero",
    category: "composition",
    title: "특정 아군 영웅과의 궁합",
    question: "특정 아군 영웅과 함께할 때 내 승률이 달라지는가?",
    rule: "ally_hero present → compare win rate",
    requiredData: ["result", "team_comp"],
    minSamples: 60,
    priority: "high",
  },
  {
    id: "comp-enemy-hero",
    category: "composition",
    title: "특정 상대 영웅 상성",
    question: "특정 상대 영웅이 있을 때 내 승률이나 데스가 달라지는가?",
    rule: "enemy_hero present → compare result and deaths",
    requiredData: ["result", "team_comp", "player_stats"],
    minSamples: 60,
    priority: "high",
  },
  {
    id: "comp-ally-myhero",
    category: "composition",
    title: "아군 영웅 × 내 영웅",
    question: "내가 선택한 영웅과 특정 아군 영웅의 조합에서 승률 차이가 있는가?",
    rule: "ally_hero × my_hero → interaction effect",
    requiredData: ["result", "team_comp", "hero"],
    minSamples: 80,
    priority: "high",
  },
  {
    id: "comp-enemy-myhero",
    category: "composition",
    title: "상대 영웅 × 내 영웅",
    question: "내 영웅이 특정 상대 영웅을 만났을 때 성과 차이가 있는가?",
    rule: "enemy_hero × my_hero → interaction effect",
    requiredData: ["result", "team_comp", "hero"],
    minSamples: 80,
    priority: "high",
  },
  {
    id: "comp-full-team",
    category: "composition",
    title: "특정 아군 조합 패턴",
    question: "특정 역할/영웅 조합 패턴에서 내 승률이 반복적으로 달라지는가?",
    rule: "team_composition cluster → compare win rate",
    requiredData: ["result", "team_comp"],
    minSamples: 100,
    priority: "explore",
  },
  {
    id: "comp-mode",
    category: "composition",
    title: "조합 × 게임 모드",
    question: "같은 조합 유형이라도 게임 모드에 따라 효과가 달라지는가?",
    rule: "composition cluster × game_mode → interaction effect",
    requiredData: ["result", "team_comp", "mode"],
    minSamples: 100,
    priority: "explore",
  },

  {
    id: "meta-patch-before-after",
    category: "meta",
    title: "패치 전/후 내 성과",
    question: "같은 영웅의 내 성과가 패치 전후로 실제 변했는가?",
    rule: "patch boundary × my_hero → compare personal metrics",
    requiredData: ["result", "hero", "player_stats", "patch"],
    minSamples: 50,
    priority: "high",
  },
  {
    id: "meta-official-winrate",
    category: "meta",
    title: "공식 승률 변화와 내 승률",
    question: "영웅 공식 승률 변화와 내 개인 승률 변화가 같은 방향인가?",
    rule: "official_winrate_delta vs personal_winrate_delta",
    requiredData: ["result", "hero", "meta_snapshot"],
    minSamples: 60,
    priority: "high",
  },
  {
    id: "meta-pickrate",
    category: "meta",
    title: "픽률 변화와 내 경기",
    question: "영웅 픽률이 급변한 기간에 내 매치업이나 승률도 변하는가?",
    rule: "official_pickrate_delta → personal matchup/result shift",
    requiredData: ["result", "team_comp", "meta_snapshot"],
    minSamples: 70,
    priority: "medium",
  },
  {
    id: "meta-banrate",
    category: "meta",
    title: "밴률 변화와 내 경기",
    question: "밴률 변화가 큰 패치 구간에서 내 영웅 선택과 승률이 달라지는가?",
    rule: "banrate_delta × my_hero → result shift",
    requiredData: ["result", "hero", "meta_snapshot"],
    minSamples: 70,
    priority: "explore",
  },
  {
    id: "meta-personal-vs-tier",
    category: "meta",
    title: "내 변화와 동일 티어 평균 비교",
    question: "내 성과 변화가 동일 티어 전체 변화보다 큰 개인적 변화인가?",
    rule: "personal_delta - same_tier_meta_delta",
    requiredData: ["result", "player_stats", "profile_snapshot", "meta_snapshot"],
    minSamples: 80,
    priority: "high",
  },

  {
    id: "trend-recent-deaths",
    category: "trend",
    title: "최근 승률 변화와 데스 변화",
    question: "최근 승률 변화 구간에서 데스/10분 변화가 함께 반복되는가?",
    rule: "rolling_winrate_delta vs rolling_deaths_per_10_delta",
    requiredData: ["result", "player_stats"],
    minSamples: 50,
    priority: "high",
  },
  {
    id: "trend-recent-accuracy",
    category: "trend",
    title: "최근 승률 변화와 명중률",
    question: "최근 승률 변화 구간에서 명중률이 의미 있게 변하는가?",
    rule: "rolling_winrate_delta vs rolling_accuracy_delta",
    requiredData: ["result", "hero_detail"],
    minSamples: 50,
    priority: "medium",
  },
  {
    id: "trend-rank",
    category: "trend",
    title: "티어 변화 전후 플레이 지표",
    question: "티어 상승 또는 하락 전후에 반복적으로 변하는 개인 지표가 있는가?",
    rule: "rank_snapshot boundary → compare rolling personal metrics",
    requiredData: ["result", "player_stats", "profile_snapshot"],
    minSamples: 70,
    priority: "medium",
  },
  {
    id: "trend-duo",
    category: "trend",
    title: "듀오 여부와 승률",
    question: "같이 플레이한 경기와 각자 플레이한 경기의 승률과 성과 차이가 있는가?",
    rule: "duo_link present → compare result and personal metrics",
    requiredData: ["result", "duo_link"],
    minSamples: 50,
    priority: "high",
  },

  {
    id: "perf-kda",
    category: "performance",
    title: "KDA와 승률",
    question: "내 KDA가 개인 평균보다 높은 경기에서 승률이 달라지는가?",
    rule: "(elims + assists) / max(deaths, 1) > personal_baseline → compare win rate",
    requiredData: ["result", "player_stats"],
    minSamples: 30,
    priority: "high",
  },
  {
    id: "perf-damage-per-elim",
    category: "performance",
    title: "처치당 피해 효율",
    question: "처치 한 번을 만들기 위해 필요한 피해량이 낮은 경기에서 승률이 달라지는가?",
    rule: "damage / max(elims, 1) → compare result",
    requiredData: ["result", "player_stats"],
    minSamples: 35,
    priority: "medium",
  },
  {
    id: "perf-heal-per-death",
    category: "performance",
    title: "데스당 치유 효율",
    question: "죽기 전까지 만들어낸 치유량이 높은 경기에서 승률이 달라지는가?",
    rule: "healing / max(deaths, 1) → compare result",
    requiredData: ["result", "player_stats"],
    minSamples: 35,
    priority: "medium",
  },
  {
    id: "perf-mitigation-per-death",
    category: "performance",
    title: "데스당 피해 경감",
    question: "데스 대비 피해 경감량이 높은 경기에서 승률이 달라지는가?",
    rule: "mitigation / max(deaths, 1) → compare result",
    requiredData: ["result", "player_stats"],
    minSamples: 35,
    priority: "explore",
  },
  {
    id: "perf-stat-balance",
    category: "performance",
    title: "공격·생존 지표 균형",
    question: "딜만 높거나 생존만 높은 경기보다 두 지표가 균형 잡힌 경기의 승률이 다른가?",
    rule: "offense_score × survival_score → interaction with result",
    requiredData: ["result", "player_stats"],
    minSamples: 50,
    priority: "high",
  },
  {
    id: "perf-low-death-high-output",
    category: "performance",
    title: "저데스·고기여 경기",
    question: "평균 이하 데스와 평균 이상 핵심 기여를 동시에 달성한 경기의 승률은 어떤가?",
    rule: "deaths < baseline AND output > baseline → compare win rate",
    requiredData: ["result", "player_stats"],
    minSamples: 40,
    priority: "high",
  },
  {
    id: "perf-output-volatility",
    category: "performance",
    title: "퍼포먼스 변동성",
    question: "개인 지표의 경기별 변동폭이 커지는 기간에 승률도 불안정해지는가?",
    rule: "rolling personal metric variance vs rolling result variance",
    requiredData: ["result", "player_stats"],
    minSamples: 60,
    priority: "explore",
  },
  {
    id: "perf-hero-switch-count",
    category: "performance",
    title: "영웅 교체 횟수와 승률",
    question: "한 경기에서 영웅을 자주 바꾼 경기와 적게 바꾼 경기의 승률이 다른가?",
    rule: "hero_switch_count → grouped win rate",
    requiredData: ["result", "hero_detail"],
    minSamples: 45,
    priority: "medium",
  },
  {
    id: "perf-first-death-impact",
    category: "performance",
    title: "첫 데스와 경기 결과",
    question: "내가 팀의 첫 데스를 기록한 경기에서 승률이 달라지는가?",
    rule: "my_first_team_death → compare result",
    requiredData: ["result", "replay_timeline"],
    minSamples: 50,
    priority: "high",
  },
  {
    id: "perf-first-elim-impact",
    category: "performance",
    title: "첫 킬 관여와 경기 결과",
    question: "첫 교전에서 처치에 관여한 경기의 승률이 달라지는가?",
    rule: "first_fight_elim_participation → compare result",
    requiredData: ["result", "replay_timeline"],
    minSamples: 50,
    priority: "high",
  },
  {
    id: "perf-ult-efficiency",
    category: "performance",
    title: "궁극기 효율과 승률",
    question: "궁극기 사용 대비 핵심 기여가 높은 경기에서 승률이 달라지는가?",
    rule: "ultimate_value_metric → compare result",
    requiredData: ["result", "hero_detail"],
    minSamples: 60,
    priority: "explore",
  },
  {
    id: "perf-clutch-late-fight",
    category: "performance",
    title: "후반 교전 기여도",
    question: "후반 핵심 교전에서 내 생존과 처치 관여가 높은 경기에서 승률이 달라지는가?",
    rule: "late_fight_survival × elim_participation → result",
    requiredData: ["result", "replay_timeline"],
    minSamples: 70,
    priority: "explore",
  },

  {
    id: "team-damage-rank",
    category: "team_relative",
    title: "팀 내 피해 순위",
    question: "팀 내 피해량 순위가 높을수록 승률이 달라지는가?",
    rule: "damage_rank_within_team → grouped win rate",
    requiredData: ["result", "player_stats"],
    minSamples: 35,
    priority: "medium",
  },
  {
    id: "team-heal-rank",
    category: "team_relative",
    title: "팀 내 치유 순위",
    question: "팀 내 치유량 순위가 승률과 어떤 관계를 가지는가?",
    rule: "healing_rank_within_team → grouped win rate",
    requiredData: ["result", "player_stats"],
    minSamples: 35,
    priority: "medium",
  },
  {
    id: "team-death-rank",
    category: "team_relative",
    title: "팀 내 데스 순위",
    question: "팀에서 데스가 많은 편인 경기와 적은 편인 경기의 승률이 다른가?",
    rule: "death_rank_within_team → grouped win rate",
    requiredData: ["result", "player_stats"],
    minSamples: 35,
    priority: "high",
  },
  {
    id: "team-elim-rank",
    category: "team_relative",
    title: "팀 내 처치 순위",
    question: "팀 내 처치 순위와 승률의 관계가 영웅별로 달라지는가?",
    rule: "elim_rank_within_team × my_hero → result",
    requiredData: ["result", "player_stats", "hero"],
    minSamples: 50,
    priority: "medium",
  },
  {
    id: "team-damage-diff-enemy",
    category: "team_relative",
    title: "양 팀 총 피해 차이",
    question: "우리 팀과 상대 팀의 총 피해량 차이가 승패와 얼마나 연결되는가?",
    rule: "ally_total_damage - enemy_total_damage → result",
    requiredData: ["result", "player_stats"],
    minSamples: 40,
    priority: "high",
  },
  {
    id: "team-heal-diff-enemy",
    category: "team_relative",
    title: "양 팀 총 치유 차이",
    question: "우리 팀과 상대 팀의 총 치유량 차이가 승패와 어떤 관계가 있는가?",
    rule: "ally_total_healing - enemy_total_healing → result",
    requiredData: ["result", "player_stats"],
    minSamples: 40,
    priority: "medium",
  },
  {
    id: "team-death-diff-enemy",
    category: "team_relative",
    title: "양 팀 총 데스 차이",
    question: "양 팀 총 데스 차이가 실제 경기 결과와 얼마나 일치하는가?",
    rule: "ally_total_deaths - enemy_total_deaths → result",
    requiredData: ["result", "player_stats"],
    minSamples: 40,
    priority: "high",
  },
  {
    id: "team-role-pair-balance",
    category: "team_relative",
    title: "같은 역할 2인 성과 균형",
    question: "같은 역할군 두 명의 성과가 균형적인 경기와 한 명에게 편중된 경기의 승률이 다른가?",
    rule: "within_role_pair_gap → compare win rate",
    requiredData: ["result", "player_stats", "team_comp"],
    minSamples: 60,
    priority: "explore",
  },
  {
    id: "team-carry-dependency",
    category: "team_relative",
    title: "팀 캐리 의존도",
    question: "팀 핵심 지표가 한 명에게 과도하게 집중된 경기에서 승률이 달라지는가?",
    rule: "max_player_share_of_team_output → compare result",
    requiredData: ["result", "player_stats"],
    minSamples: 60,
    priority: "explore",
  },
  {
    id: "team-balanced-output",
    category: "team_relative",
    title: "팀 기여도 균형",
    question: "팀원들의 기여도가 고르게 분포된 경기에서 승률이 달라지는가?",
    rule: "team_output_entropy → compare result",
    requiredData: ["result", "player_stats"],
    minSamples: 60,
    priority: "explore",
  },

  {
    id: "context-duration-bucket",
    category: "context",
    title: "경기 시간 구간별 승률",
    question: "짧은 경기, 보통 경기, 긴 경기에서 승률이 달라지는가?",
    rule: "match_duration_bucket → grouped win rate",
    requiredData: ["result", "manual_context"],
    minSamples: 45,
    priority: "medium",
  },
  {
    id: "context-overtime",
    category: "context",
    title: "연장전 경기 승률",
    question: "연장전까지 간 경기와 그렇지 않은 경기의 승률이 다른가?",
    rule: "overtime_flag → compare win rate",
    requiredData: ["result", "replay_timeline"],
    minSamples: 50,
    priority: "medium",
  },
  {
    id: "context-time-of-day",
    category: "context",
    title: "시간대별 승률",
    question: "오전, 오후, 저녁, 심야 플레이 시간대에 따라 승률이 달라지는가?",
    rule: "played_at hour bucket → grouped win rate",
    requiredData: ["result", "session_context"],
    minSamples: 70,
    priority: "medium",
  },
  {
    id: "context-weekday",
    category: "context",
    title: "요일별 승률",
    question: "평일과 주말 또는 특정 요일에 따라 승률이 반복적으로 달라지는가?",
    rule: "played_at weekday → grouped win rate",
    requiredData: ["result", "session_context"],
    minSamples: 80,
    priority: "explore",
  },
  {
    id: "context-session-first-game",
    category: "context",
    title: "세션 첫 경기 효과",
    question: "게임을 켠 뒤 첫 경기의 승률과 퍼포먼스가 이후 경기와 다른가?",
    rule: "session_game_index = 1 → compare result and metrics",
    requiredData: ["result", "session_context", "player_stats"],
    minSamples: 60,
    priority: "medium",
  },
  {
    id: "context-session-game-index",
    category: "context",
    title: "연속 플레이 순번",
    question: "한 세션에서 경기 순번이 뒤로 갈수록 승률이나 데스가 변하는가?",
    rule: "session_game_index → rolling performance/result",
    requiredData: ["result", "session_context", "player_stats"],
    minSamples: 80,
    priority: "high",
  },
  {
    id: "context-after-win",
    category: "context",
    title: "승리 직후 경기",
    question: "직전 경기를 이긴 뒤 다음 경기의 승률과 퍼포먼스가 달라지는가?",
    rule: "previous_result = win → next_match outcome",
    requiredData: ["result", "session_context"],
    minSamples: 70,
    priority: "explore",
  },
  {
    id: "context-after-loss",
    category: "context",
    title: "패배 직후 경기",
    question: "직전 경기를 진 뒤 다음 경기의 승률과 퍼포먼스가 달라지는가?",
    rule: "previous_result = loss → next_match outcome",
    requiredData: ["result", "session_context"],
    minSamples: 70,
    priority: "high",
  },
  {
    id: "context-win-streak",
    category: "context",
    title: "연승 중 성과 변화",
    question: "연승이 이어지는 동안 영웅 선택이나 개인 지표가 변하는가?",
    rule: "win_streak_length → hero choice and personal metrics",
    requiredData: ["result", "session_context", "player_stats"],
    minSamples: 80,
    priority: "explore",
  },
  {
    id: "context-loss-streak",
    category: "context",
    title: "연패 중 성과 변화",
    question: "연패가 길어질수록 데스, 영웅 교체, 승률 회복 가능성이 변하는가?",
    rule: "loss_streak_length → performance and next result",
    requiredData: ["result", "session_context", "player_stats"],
    minSamples: 80,
    priority: "high",
  },
  {
    id: "context-map-repeat",
    category: "context",
    title: "같은 맵 재등장 효과",
    question: "짧은 기간에 같은 맵을 다시 만났을 때 이전 경기 결과가 다음 성과와 연결되는가?",
    rule: "recent_same_map_result → next_same_map result",
    requiredData: ["result", "map", "session_context"],
    minSamples: 80,
    priority: "explore",
  },
  {
    id: "context-mode-hero",
    category: "context",
    title: "게임 모드 × 내 영웅",
    question: "같은 영웅이라도 게임 모드에 따라 개인 성과와 승률이 달라지는가?",
    rule: "game_mode × my_hero → interaction effect",
    requiredData: ["result", "mode", "hero"],
    minSamples: 70,
    priority: "high",
  },

  {
    id: "comp-ally-support-pair",
    category: "composition",
    title: "아군 지원 조합",
    question: "특정 지원 영웅 2인 조합에서 내 승률이나 생존력이 달라지는가?",
    rule: "ally_support_pair → result and deaths",
    requiredData: ["result", "team_comp", "player_stats"],
    minSamples: 80,
    priority: "high",
  },
  {
    id: "comp-enemy-support-pair",
    category: "composition",
    title: "상대 지원 조합",
    question: "상대 지원 영웅 2인 조합에 따라 내 성과와 승률이 달라지는가?",
    rule: "enemy_support_pair → result and personal metrics",
    requiredData: ["result", "team_comp", "player_stats"],
    minSamples: 80,
    priority: "high",
  },
  {
    id: "comp-tank-matchup",
    category: "composition",
    title: "탱커 매치업",
    question: "양 팀 탱커 매치업에 따라 내 승률과 역할 수행 지표가 달라지는가?",
    rule: "ally_tank × enemy_tank → result",
    requiredData: ["result", "team_comp"],
    minSamples: 80,
    priority: "high",
  },
  {
    id: "comp-mirror",
    category: "composition",
    title: "미러 조합 여부",
    question: "양 팀 핵심 영웅이 겹치는 미러 구도에서 내 승률이 달라지는가?",
    rule: "composition_mirror_score → compare result",
    requiredData: ["result", "team_comp"],
    minSamples: 70,
    priority: "medium",
  },
  {
    id: "comp-style-cluster",
    category: "composition",
    title: "조합 스타일별 승률",
    question: "다이브, 포크, 난전형 등 조합 스타일에 따라 내 승률이 달라지는가?",
    rule: "composition_style_cluster → grouped win rate",
    requiredData: ["result", "team_comp"],
    minSamples: 100,
    priority: "high",
  },
  {
    id: "comp-enemy-counter-density",
    category: "composition",
    title: "상대 카운터 밀도",
    question: "내 영웅을 상대하기 좋은 영웅이 상대 팀에 많을수록 내 성과가 떨어지는가?",
    rule: "enemy_counter_count(my_hero) → performance/result",
    requiredData: ["result", "hero", "team_comp", "meta_snapshot"],
    minSamples: 100,
    priority: "high",
  },
  {
    id: "comp-ally-synergy-density",
    category: "composition",
    title: "아군 시너지 밀도",
    question: "내 영웅과 시너지가 높은 영웅이 아군에 많을수록 승률이 달라지는가?",
    rule: "ally_synergy_count(my_hero) → result",
    requiredData: ["result", "hero", "team_comp", "meta_snapshot"],
    minSamples: 100,
    priority: "medium",
  },
  {
    id: "comp-hero-pool-diversity",
    category: "composition",
    title: "팀 영웅 다양성",
    question: "한 경기에서 팀의 영웅 교체 폭이 큰 경우와 작은 경우 승률이 다른가?",
    rule: "team_unique_hero_count → compare result",
    requiredData: ["result", "team_comp", "replay_timeline"],
    minSamples: 90,
    priority: "explore",
  },
  {
    id: "comp-same-core-continuity",
    category: "composition",
    title: "연속 경기 핵심 조합 유지",
    question: "같은 듀오/파티에서 핵심 조합을 연속 유지했을 때 성과가 개선되는가?",
    rule: "core_comp_continuity_across_session → result",
    requiredData: ["result", "team_comp", "session_context"],
    minSamples: 90,
    priority: "explore",
  },
  {
    id: "comp-swap-response",
    category: "composition",
    title: "상대 교체에 대한 대응",
    question: "상대 핵심 영웅 교체 후 빠르게 영웅을 바꾼 경기에서 결과가 달라지는가?",
    rule: "response_time_to_enemy_swap → result",
    requiredData: ["result", "replay_timeline", "team_comp"],
    minSamples: 100,
    priority: "explore",
  },
  {
    id: "comp-team-comp-stability",
    category: "composition",
    title: "아군 조합 안정성",
    question: "아군 영웅 구성이 자주 바뀌는 경기와 안정적인 경기의 승률이 다른가?",
    rule: "ally_comp_change_count → compare result",
    requiredData: ["result", "replay_timeline", "team_comp"],
    minSamples: 90,
    priority: "medium",
  },
  {
    id: "comp-enemy-comp-stability",
    category: "composition",
    title: "상대 조합 안정성",
    question: "상대 팀의 영웅 교체 빈도가 경기 결과와 어떤 관계를 가지는가?",
    rule: "enemy_comp_change_count → compare result",
    requiredData: ["result", "replay_timeline", "team_comp"],
    minSamples: 90,
    priority: "explore",
  },

  {
    id: "meta-buff-response",
    category: "meta",
    title: "버프 이후 개인 적응",
    question: "내 주 영웅이 상향된 뒤 개인 승률과 플레이 지표가 실제로 개선되는가?",
    rule: "buff_patch boundary × my_hero → personal delta",
    requiredData: ["result", "hero", "player_stats", "patch"],
    minSamples: 60,
    priority: "high",
  },
  {
    id: "meta-nerf-response",
    category: "meta",
    title: "너프 이후 개인 적응",
    question: "내 주 영웅이 하향된 뒤 승률 하락이 얼마나 지속되고 회복되는가?",
    rule: "nerf_patch boundary × my_hero → rolling personal delta",
    requiredData: ["result", "hero", "player_stats", "patch"],
    minSamples: 60,
    priority: "high",
  },
  {
    id: "meta-hotfix",
    category: "meta",
    title: "핫픽스 직후 변화",
    question: "소규모 핫픽스 직후 며칠 동안 내 승률이나 영웅 선택이 급변하는가?",
    rule: "days_from_hotfix → personal metrics/result",
    requiredData: ["result", "patch", "hero"],
    minSamples: 80,
    priority: "medium",
  },
  {
    id: "meta-adaptation-speed",
    category: "meta",
    title: "패치 적응 속도",
    question: "새 패치 직후 몇 경기 안에 내 성과가 안정되는가?",
    rule: "matches_since_patch → rolling variance and result",
    requiredData: ["result", "patch", "player_stats"],
    minSamples: 100,
    priority: "high",
  },
  {
    id: "meta-meta-divergence",
    category: "meta",
    title: "메타와 내 강점의 불일치",
    question: "공식 메타에서 약한 영웅이지만 나에게는 잘 맞는 경우가 반복적으로 존재하는가?",
    rule: "personal_winrate - official_winrate → hero-specific divergence",
    requiredData: ["result", "hero", "meta_snapshot"],
    minSamples: 100,
    priority: "high",
  },
  {
    id: "meta-pickrate-quartile",
    category: "meta",
    title: "메타 픽률 구간과 내 성과",
    question: "픽률이 높은 메타 영웅을 상대하거나 사용할 때 내 승률이 달라지는가?",
    rule: "official_pickrate_quartile × hero presence → result",
    requiredData: ["result", "team_comp", "meta_snapshot"],
    minSamples: 100,
    priority: "medium",
  },
  {
    id: "meta-map-pool-shift",
    category: "meta",
    title: "맵 풀 변화 영향",
    question: "시즌 또는 패치의 맵 풀 변화가 내 전체 승률 변화에 영향을 주는가?",
    rule: "map_pool_period → personal result distribution",
    requiredData: ["result", "map", "patch"],
    minSamples: 120,
    priority: "explore",
  },
  {
    id: "meta-patch-volatility",
    category: "meta",
    title: "패치 규모와 성과 변동성",
    question: "변경량이 큰 패치일수록 내 경기 성과 변동폭도 커지는가?",
    rule: "patch_change_magnitude → rolling personal variance",
    requiredData: ["result", "patch", "player_stats"],
    minSamples: 120,
    priority: "explore",
  },

  {
    id: "trend-session-fatigue",
    category: "trend",
    title: "장시간 세션 피로",
    question: "한 세션이 길어질수록 데스와 승률이 악화되는가?",
    rule: "minutes_since_session_start → performance/result",
    requiredData: ["result", "session_context", "player_stats"],
    minSamples: 80,
    priority: "high",
  },
  {
    id: "trend-session-warmup",
    category: "trend",
    title: "워밍업 구간",
    question: "세션 초반 몇 경기 이후 퍼포먼스가 안정적으로 좋아지는 패턴이 있는가?",
    rule: "session_game_index 1..N → personal metric curve",
    requiredData: ["result", "session_context", "player_stats"],
    minSamples: 80,
    priority: "medium",
  },
  {
    id: "trend-streak-recovery",
    category: "trend",
    title: "연패 후 회복 패턴",
    question: "연패가 끝나는 경기에서 평소와 다르게 변하는 영웅 선택이나 플레이 지표가 있는가?",
    rule: "loss_streak_end match → compare hero and metrics",
    requiredData: ["result", "session_context", "player_stats", "hero"],
    minSamples: 100,
    priority: "explore",
  },
  {
    id: "trend-hero-specialization",
    category: "trend",
    title: "주력 영웅 집중도",
    question: "최근 경기에서 특정 영웅 사용 비중이 높아질수록 해당 영웅 성과가 개선되는가?",
    rule: "rolling hero pick share → hero-specific performance",
    requiredData: ["result", "hero", "hero_detail"],
    minSamples: 80,
    priority: "high",
  },
  {
    id: "trend-hero-pool-breadth",
    category: "trend",
    title: "영웅 풀 넓이",
    question: "일정 기간에 사용하는 영웅 수가 많을 때와 적을 때 승률이 다른가?",
    rule: "rolling unique hero count → compare result",
    requiredData: ["result", "hero"],
    minSamples: 100,
    priority: "medium",
  },
  {
    id: "trend-stat-variance",
    category: "trend",
    title: "최근 플레이 안정성",
    question: "최근 개인 지표의 분산이 줄어드는 시기에 승률이 안정되는가?",
    rule: "rolling metric variance → rolling winrate variance",
    requiredData: ["result", "player_stats"],
    minSamples: 80,
    priority: "medium",
  },
  {
    id: "trend-rank-up-preceding",
    category: "trend",
    title: "티어 상승 전 선행 지표",
    question: "티어가 오르기 전 여러 경기에서 먼저 개선되는 지표가 반복되는가?",
    rule: "pre-rank-up rolling metrics → identify leading indicators",
    requiredData: ["result", "profile_snapshot", "player_stats"],
    minSamples: 120,
    priority: "high",
  },
  {
    id: "trend-rank-down-preceding",
    category: "trend",
    title: "티어 하락 전 선행 지표",
    question: "티어가 내려가기 전 반복적으로 악화되는 개인 지표가 있는가?",
    rule: "pre-rank-down rolling metrics → identify leading indicators",
    requiredData: ["result", "profile_snapshot", "player_stats"],
    minSamples: 120,
    priority: "high",
  },
  {
    id: "trend-duo-synergy-by-hero",
    category: "trend",
    title: "듀오 × 내 영웅 시너지",
    question: "듀오일 때 특히 성과가 좋아지거나 나빠지는 내 영웅이 있는가?",
    rule: "duo_link × my_hero → interaction effect",
    requiredData: ["result", "duo_link", "hero"],
    minSamples: 80,
    priority: "high",
  },
  {
    id: "trend-duo-vs-solo-map",
    category: "trend",
    title: "듀오/솔로 × 맵",
    question: "같은 맵에서도 듀오 플레이와 솔로 플레이의 승률 차이가 있는가?",
    rule: "duo_link × map_name → interaction effect",
    requiredData: ["result", "duo_link", "map"],
    minSamples: 100,
    priority: "medium",
  },
];

export const PREDEFINED_HYPOTHESIS_COUNT = PREDEFINED_HYPOTHESES.length;
