// Fixed FE display labels keyed only by stable Personal OCR metric_key.
// label_raw from OCR is intentionally not used for user-facing text.
export const PERSONAL_METRIC_LABELS: Record<string, string> = {
  "abduction_kills": "납치한다냥으로 처치",
  "accretion_accuracy": "강착 명중률",
  "accretion_kills": "강착으로 처치",
  "adaptive_shield_generated": "생성한 적응형 보호막",
  "aimed_shot_accuracy": "정조준 명중률",
  "aimed_shot_kills": "정조준으로 처치",
  "ally_coalescence_efficiency": "아군 융화 활용도",
  "amplification_matrix_assists": "증폭 매트릭스 지원",
  "annihilation_efficiency": "절멸 활용도",
  "annihilation_kills": "절멸로 처치",
  "artillery_kills": "포격으로 처치",
  "assault_mode_kills": "강습 모드로 처치",
  "average_charge": "평균 충전 계수",
  "average_energy": "평균 에너지",
  "barrage_kills": "포화로 처치",
  "barrier_sanctuary_absorbed": "결계 성역으로 흡수",
  "biotic_grenade_kills": "생체 수류탄 처치",
  "biotic_orb_healing": "생체 구슬로 치유",
  "biotic_orb_kills": "생체 구슬로 처치",
  "blade_projectile_accuracy": "칼날 투영 명중률",
  "blade_projectile_kills": "칼날 투영 처치",
  "blaster_kills": "블라스터로 처치",
  "blizzard_kills": "눈보라로 처치",
  "bob_kills": "B.O.B.으로 처치",
  "bonus_ultimate_charge": "추가 궁극기 충전 획득",
  "booster_kills": "부스터로 처치",
  "cage_fight_kills": "케이지 혈투로 처치",
  "call_mech_kills": "메카 호출로 처치",
  "carnage_kills": "도륙으로 처치",
  "chain_hook_accuracy": "사슬 갈고리 명중률",
  "chain_hook_kills": "사슬 갈고리로 처치",
  "charge_kills": "돌진으로 처치",
  "charged_shot_accuracy": "충전된 사격 명중률",
  "charged_shot_critical_hit_accuracy": "충전된 사격 치명타 명중률",
  "charged_shot_kills": "충전된 사격으로 처치",
  "coalescence_healing": "융화로 치유",
  "coalescence_kills": "융화로 처치",
  "concussion_mine_kills": "충격 지뢰로 처치",
  "concussive_charge_kills": "진동 폭약으로 처치",
  "critical_damage": "치명타로 준 피해",
  "critical_hit_accuracy": "치명타 명중률",
  "critical_hit_damage": "치명타로 준 피해",
  "critical_hit_kills": "치명타 처치",
  "critical_hits": "치명타",
  "crystal_charge_damage": "수정 발사 피해",
  "cyber_fragment_grenade_damage": "사이버 파편 수류탄으로 준 피해",
  "damage_amplified": "공격력 증폭",
  "damage_boost_beam_usage": "증폭 광선 사용",
  "dancing_blaze_kills": "춤추는 불꽃으로 처치",
  "death_blossom_kills": "죽음의 꽃으로 처치",
  "deaths_prevented": "불사 장치로 사망 저지",
  "direct_hit_accuracy": "직격 명중률",
  "disruptor_shot_kills": "분열 사격으로 처치",
  "dragonblade_kills": "용검으로 처치",
  "dragonstrike_kills": "용의 일격으로 처치",
  "drill_dash_kills": "드릴 돌진 처치",
  "duplicate_kills": "복제로 처치",
  "dynamite_kills": "다이너마이트로 처치",
  "earthshatter_hits": "대지분쇄 명중",
  "earthshatter_stuns": "대지분쇄로 기절",
  "emp_kills": "EMP로 처치",
  "enemies_bound": "속박한 적",
  "enemies_frozen": "얼린 적",
  "enemies_hacked": "해킹한 적",
  "enemies_ignited": "불태운 적",
  "enemies_slept": "재운 적",
  "enemies_trapped": "덫에 걸린 적",
  "enemy_coalescence_efficiency": "적 융화 활용도",
  "energy_javelin_accuracy": "투창 명중률",
  "energy_javelin_kills": "투창으로 처치",
  "environmental_kills": "환경 요소로 처치",
  "execution_accuracy": "처형 명중률",
  "execution_kills": "처형으로 처치",
  "fan_the_flames_accuracy": "불난 데 부채질 명중률",
  "final_blows": "결정타",
  "fire_strike_accuracy": "화염 강타 명중률",
  "fire_strike_kills": "화염 강타로 처치",
  "flashbang_kills": "섬광탄으로 처치",
  "flight_uptime": "비행 시간 비율",
  "focusing_beam_accuracy": "광선 집중 명중률",
  "focusing_beam_kills": "광선 집중으로 처치",
  "fusion_repeater_accuracy": "융합 연발총 명중률",
  "fusion_repeater_kills": "융합 연발총으로 처치",
  "grapple_kills": "갈고리 고정으로 처치",
  "gravity_flux_kills": "중력 붕괴로 처치",
  "guardian_wave_kills": "수호의 파도로 처치",
  "hammer_kills": "망치로 처치",
  "healing_accuracy": "치유 명중률",
  "healing_amplified": "치유 증폭",
  "healing_beam_usage": "치유 광선 사용",
  "healing_boost_usage": "치유 증폭 사용",
  "healing_hat_accuracy": "치유의 삿갓 명중률",
  "healing_hat_healing": "치유의 삿갓으로 치유",
  "healing_ofuda_accuracy": "치유의 부적 명중률",
  "healing_prevented": "차단한 치유",
  "healing_pylon_healing": "태양석 치유",
  "healing_pylon_uptime": "태양석 활성 시간 비율",
  "healing_wave_healing_amplified": "회복의 물결 치유 강화",
  "helix_rocket_accuracy": "나선 로켓 명중률",
  "helix_rocket_kills": "나선 로켓으로 처치",
  "high_energy_kills": "고에너지로 처치",
  "high_noon_kills": "황야의 무법자로 처치",
  "icicle_accuracy": "고드름 명중률",
  "icicle_critical_hit_accuracy": "고드름 치명타 명중률",
  "inspire_triggers": "격려 발동",
  "inspire_uptime": "격려 활성 시간 비율",
  "jagged_blade_accuracy": "톱니칼 명중률",
  "jagged_blade_kills": "톱니칼로 처치",
  "jagged_wall_damage": "날카로운 저항으로 준 피해",
  "javelin_spin_kills": "수호의 창으로 처치",
  "joyride_air_launch_accuracy": "조이라이드 공중 발사 명중률",
  "joyride_damage": "조이라이드로 준 피해",
  "joyride_ground_launch_accuracy": "조이라이드 지상 발사 명중률",
  "joyride_kills": "조이라이드로 처치",
  "jump_pack_kills": "점프 팩으로 처치",
  "knockback_kills": "밀쳐내기로 처치",
  "kitsune_rush_assists": "여우길 지원",
  "kunai_kills": "쿠나이로 처치",
  "lasso_shot_damage": "올가미 사격으로 준 피해",
  "life_grip_saves": "구원의 손길로 선방",
  "lifeline_healing": "생명줄 치유",
  "lifeline_usage": "생명줄 사용",
  "limit_break_kills": "한계 돌파로 처치",
  "long_range_final_blows": "장거리 결정타",
  "low_health_recalls": "낮은 생명력 회상",
  "low_health_translocates": "낮은 생명력일 때 순간이동",
  "lunge_damage": "덤벼들기로 준 피해",
  "meteor_strike_kills": "파멸의 일격으로 처치",
  "micro_missiles_kills": "마이크로 미사일로 처치",
  "molten_core_kills": "초고열 용광로로 처치",
  "nano_boost_assists": "나노 강화제 지원",
  "negative_effects_cleansed": "부정적인 효과 정화",
  "objective_contest_time": "거점 격돌 시간",
  "onslaught_uptime": "맹공 활성 시간 비율",
  "orbital_ray_assists": "궤도 광선 지원",
  "orbital_ray_healing": "궤도 광선으로 치유",
  "overclock_kills": "오버클럭으로 처치",
  "overhealth_generated": "생성한 추가 생명력",
  "overhealth_provided": "추가 생명력 제공",
  "override_protocol_kills": "오버라이드 프로토콜로 처치",
  "overrun_kills": "돌파로 처치",
  "pathfinder_kills": "개척자로 처치",
  "pig_pen_kills": "돼재앙으로 처치",
  "piledriver_kills": "파일드라이버로 처치",
  "play_time": "플레이 시간",
  "players_knocked_back": "밀쳐낸 플레이어",
  "players_resurrected": "부활한 플레이어",
  "players_saved": "구한 플레이어",
  "players_teleported": "순간이동한 플레이어",
  "primal_rage_kills": "원시의 분노로 처치",
  "primary_fire_accuracy": "기본 발사 명중률",
  "projected_barriers_applied": "방벽 씌운 플레이어",
  "pulsar_torpedoes_damage": "펄사 어뢰로 준 피해",
  "pulsar_torpedoes_healing": "펄사 어뢰로 치유",
  "pulse_bomb_attach_rate": "폭탄 부착률",
  "pulse_bomb_kills": "펄스 폭탄으로 처치",
  "pummel_accuracy": "응징 명중률",
  "pummel_kills": "응징으로 처치",
  "purr_support": "골골송 지원",
  "ravenous_vortex_kills": "탐식의 소용돌이로 처치",
  "recon_assists": "처치 시야 지원",
  "recon_mode_kills": "수색 모드로 처치",
  "reflected_damage": "반사한 피해",
  "rip_tire_kills": "죽이는 타이어로 처치",
  "rocket_punch_kills": "로켓 펀치로 처치",
  "satsuriku_spree_kills": "광란의 살육으로 처치",
  "scoped_accuracy": "저격 명중률",
  "scoped_critical_hit_accuracy": "저격 치명타 명중률",
  "scoped_critical_hit_kills": "저격 치명타 처치",
  "secondary_fire_accuracy": "보조 발사 명중률",
  "seismic_slam_kills": "지진 강타로 처치",
  "self_destruct_kills": "자폭으로 처치",
  "self_healing": "자가 치유",
  "sentry_turret_kills": "감시 포탑으로 처치",
  "shield_bash_kills": "방패 밀쳐내기로 처치",
  "shields_generated": "생성한 보호막",
  "siphon_blaster_damage": "사이펀 블라스터로 준 피해",
  "sleep_dart_accuracy": "수면총 명중률",
  "smart_excavator_hits": "스마트 굴착기 명중",
  "solo_kills": "단독 처치",
  "sound_barriers_provided": "소리 방벽 제공",
  "speed_boost_usage": "속도 증폭 사용",
  "spike_downpour_kills": "가시 소나기로 처치",
  "spirit_shuriken_accuracy": "영혼 수리검 명중률",
  "sticky_bomb_accuracy": "점착 폭탄 적중률",
  "sticky_bomb_kills": "점착 폭탄으로 처치",
  "storm_arrow_kills": "폭풍 화살로 처치",
  "sundering_blade_kills": "갈라내는 칼날 처치",
  "sunstruck_detonations": "열상 폭발",
  "surging_strike_kills": "돌진 강타로 처치",
  "swift_strike_resets": "질풍참 초기화",
  "tactical_grenade_kills": "전술 수류탄으로 처치",
  "tactical_visor_kills": "전술 조준경으로 처치",
  "tectonic_shock_kills": "지각 충격으로 처치",
  "terra_surge_kills": "대지의 창으로 처치",
  "thorn_volley_kills": "가시 연사로 처치",
  "tidal_blast_kills": "해일 폭발로 처치",
  "tracking_kills": "추적으로 처치",
  "tracking_shot_accuracy": "추적 사격 명중률",
  "transcendence_efficiency": "초월 활용도",
  "tree_of_life_healing": "생명의 나무로 치유",
  "turret_kills": "포탑으로 처치",
  "ultimate_kills": "궁극기로 처치",
  "ultimates_negated": "궁극기 차단",
  "ultimates_reflected": "궁극기 반사",
  "valkyrie_damage": "발키리로 준 피해",
  "valkyrie_healing": "발키리로 치유",
  "venom_mine_kills": "맹독 지뢰로 처치",
  "virus_accuracy": "바이러스 명중률",
  "virus_damage": "바이러스로 준 피해",
  "water_staff_direct_hits": "현무 지팡이 직격",
  "weapon_accuracy": "무기 명중률",
  "weapon_beam_accuracy": "무기 광선 명중률",
  "weapon_shot_accuracy": "무기 사격 명중률",
  "whip_shot_accuracy": "도리깨 투척 명중률",
  "whirlwind_dash_kills": "소용돌이 질주 처치",
  "wound_uptime": "부상 활성 시간 비율",
};

export function getPersonalMetricLabel(metricKey: string) {
  return PERSONAL_METRIC_LABELS[metricKey] ?? metricKey;
}
